// js/config.js

export let currentUser = null;
export const setCurrentUser = (user) => { currentUser = user; };
export const getCurrentUser = () => currentUser;

export let cachedData = {
  tasks: [],
  transactions: [],
  jadwal: null,
  settings: {},
  gamification: { xp: 0, level: 1 },
  streak: { count: 0, lastLogin: null },
  focusLogs: {}, 
  scheduleNotes: {}, 
  unlockedAchievements: [],
  subscriptions: [],
  budgets: {}
};

export const CONFIG = {
    WORK_DURATION_DEFAULT: 25 * 60,
    BREAK_DURATION_DEFAULT: 5 * 60,
    WORK_DURATION_EXAM: 50 * 60,
    BREAK_DURATION_EXAM: 10 * 60
};

export const days = ["Minggu", "Senin", "Selasa", "Rabu", "Kamis", "Jumat", "Sabtu"];

export const defaultJadwalData = {
  umum: {
    Senin: [
      { mapel: "Koding & AI", guru: "Juliana Mansur, S.Kom", time: "08.20 - 09.40", type: "produktif" },
      { mapel: "PAI & Budi Pekerti", guru: "Hapid, S.Ag", time: "10.00 - 11.20", type: "umum" },
      { mapel: "Matematika", guru: "Wijiastuti, S.Pd", time: "11.20 - 13.20", type: "umum" },
    ],
    Selasa: [ { mapel: "KOKURIKULER", guru: "Nurulia Aprilia, S.Si", time: "08.00 - 15.50", type: "kokurikuler" } ],
    Rabu: [ { mapel: "Bahasa Indonesia", guru: "Lia Siti Sholehah, S.Pd", time: "08.00 - 09.20", type: "umum" } ],
    Kamis: [ { mapel: "Sejarah", guru: "Yessy Novita D, S.Pd", time: "08.00 - 09.20", type: "umum" } ],
    Jumat: [ { mapel: "Koding & AI", guru: "Juliana Mansur, S.Kom", time: "07.45 - 09.05", type: "produktif" } ],
  },
  produktif: {
    Senin: [ { mapel: "DDPK (Juliana)", time: "08.20 - 09.40", type: "produktif" } ],
    Selasa: [ { mapel: "Projek IPAS", guru: "Nurulia Aprilia, S.Si", time: "08.00 - 11.40", type: "umum" } ],
    Rabu: [ { mapel: "Informatika", guru: "Nurdin", time: "08.00 - 09.20", type: "produktif" } ],
    Kamis: [ { mapel: "DDPK (Full Day)", guru: "Iqbal Fajar Syahbana", time: "08.00 - 15.50", type: "produktif" } ],
    Jumat: [ { mapel: "DDPK (Duma)", time: "07.45 - 10.25", type: "produktif" } ],
  },
};

export const funWords = [
    "Menyala Abangkuh! 🔥", "Gacor Parah! 🦅", "Kelas Pejabat! 🎩", "Savage! ⚔️",
    "Ez Lemon Squeezy 🍋", "Mantap Jiwa! 👻", "GG Gaming! 🎮", "Auto Kaya! 💸",
    "Mulus Banget 🧈", "Slayyy! 💅", "Top Global 🌍", "Gak Ada Obat! 💊"
];

// DATA QUOTES LENGKAP DARI SCRIPT ASLI
export const motivationalQuotes = [
    "Fokus 25 menit, hasilnya 100%. Kamu bisa! 💪",
    "Masa depanmu diciptakan oleh apa yang kamu lakukan hari ini, bukan besok.",
    "Jangan berhenti saat lelah, berhentilah saat selesai.",
    "Rasa sakit karena disiplin lebih baik daripada rasa sakit karena penyesalan.",
    "Satu jam belajar hari ini lebih berharga dari seribu jam penyesalan nanti.",
    "Versi terbaik dirimu sedang menunggumu di masa depan. Jemput dia!",
    "Kalau mimpimu tidak membuatmu takut, mungkin mimpimu kurang besar.",
    "Belajar itu memang berat, tapi kebodohan itu jauh lebih berat.",
    "Jadilah 1% lebih baik setiap harinya. Konsistensi > Intensitas.",
    "Jangan tunggu motivasi, ciptakan momentummu sendiri.",
    "Scroll sosmed tidak akan membayarmu di masa depan.",
    "Tugas yang kamu tunda hari ini akan menjadi beban di esok hari.",
    "Sukses adalah jumlah dari usaha kecil yang diulang hari demi hari.",
    "Berhenti berharap, mulai kerjakan.",
    "Waktu tidak akan menunggu. Lakukan sekarang atau tidak sama sekali.",
    "Disiplin adalah melakukan apa yang harus dilakukan, bahkan saat kamu tidak ingin.",
    "Fokus pada proses, bukan hanya pada hasil.",
    "Jangan sibuk, tapi jadilah produktif.",
    "Musuh terbesarmu adalah dirimu yang kemarin.",
    "Keajaiban terjadi saat kamu keluar dari zona nyaman.",
    "Tarik napas. Kamu sudah melakukan yang terbaik sejauh ini. 🍃",
    "Ingat minum air putih. Otak butuh cairan biar nggak nge-lag.",
    "Istirahat itu bagian dari produktivitas. Jangan lupa tidur.",
    "Gapapa pelan-pelan, yang penting jalan terus.",
    "Hari ini sulit? Gapapa, besok kita coba lagi.",
    "Kamu lebih kuat dari deadline-mu. 🔥",
    "Jangan lupa apresiasi diri sendiri setelah tugas selesai.",
    "Rejeki nggak akan ketuker, tapi kalau nggak usaha ya nggak dapet.",
    "Hidup itu seperti koding; kalau error, coba cek lagi baris demi baris.",
    "Semangat! Cicilan masa depan (dan harapan orang tua) menanti.",
    "Kita tidak bisa mengendalikan angin, tapi kita bisa mengendalikan layar.",
    "Fokus pada apa yang bisa kamu kendalikan.",
    "Kesulitan seringkali mempersiapkan orang biasa untuk takdir yang luar biasa.",
    "Jadilah seperti karang, tidak goyah meski dihantam ombak.",
    "Kebahagiaan bergantung pada dirimu sendiri.",
    "Gas terus! 🚀", "Just do it.", "Make it happen.", "Dream big, work hard.",
    "Stay hungry, stay foolish.", "Your only limit is you.", "Wake up and grind.",
    "Do it with passion or not at all.", "Action speaks louder.", "Finish what you started.",
    "Gas terus! Jangan kasih kendor! 🔥",
    "Mode serius: ON. Bantai semua tugas! 💪",
    "Tarik napas, minum air, lalu hajar! 🚀",
    "Jangan lembek! Masa depan butuh kamu yang kuat.",
    "Fokus 25 menit, hasilnya 100%. Let's go!",
    "Capek itu sementara, menyerah itu selamanya.",
    "Bangun! Mimpimu nggak bisa diraih sambil tidur.",
    "Kerjakan sekarang atau menyesal nanti.",
    "Buktikan kalau mereka salah menilai kamu.",
    "Jadilah versi terbaik dirimu hari ini.",
    "Sakit dalam perjuangan itu sementara.",
    "Jangan berhenti saat lelah, berhenti saat selesai.",
    "Kamu lebih kuat dari alasanmu untuk menyerah.",
    "Selesaikan apa yang sudah kamu mulai.",
    "Waktu tidak menunggu. Bergerak sekarang!",
    "Hari ini sulit? Besok kamu akan lebih kuat.",
    "Jadikan ragu-ragu sebagai musuhmu.",
    "Konsistensi adalah kunci. Tetap jalan!",
    "Jangan banyak mikir, banyakin aksi.",
    "Sukses butuh proses, bukan protes.",
    "Hajar tugasnya, nikmati hasilnya.",
    "Lemah itu pilihan, kuat itu keputusan.",
    "Jemput suksesmu, jangan tunggu dia datang.",
    "Keringat hari ini, senyum di masa depan.",
    "Lakukan dengan passion atau tidak sama sekali.",
    "Satu jam belajar hari ini = investasi masa depan.",
    "Disiplin adalah jembatan antara tujuan dan pencapaian.",
    "Jangan bandingkan prosesmu dengan orang lain.",
    "Usaha tidak akan mengkhianati hasil. Percaya itu.",
    "Masa depanmu diciptakan oleh apa yang kamu lakukan hari ini.",
    "Belajar itu berat, tapi kebodohan lebih berat.",
    "Kalau mimpimu tidak membuatmu takut, itu kurang besar.",
    "Jadilah 1% lebih baik setiap harinya.",
    "Kesalahan adalah bukti kamu sedang mencoba.",
    "Sukses adalah jumlah dari usaha kecil yang diulang.",
    "Musuh terbesarmu adalah dirimu yang kemarin.",
    "Fokus pada proses, hasil akan mengikuti.",
    "Jangan sibuk, tapi jadilah produktif.",
    "Keajaiban terjadi di luar zona nyaman.",
    "Pendidikan adalah senjata paling mematikan.",
    "Investasi terbaik adalah leher ke atas (ilmu).",
    "Jangan menunggu motivasi, ciptakan disiplin.",
    "Bermimpilah besar, bekerja keraslah.",
    "Waktu adalah aset yang tidak bisa diputar ulang.",
    "Jadilah seperti karang, tak goyah dihantam ombak.",
    "Kebahagiaan bergantung pada dirimu sendiri.",
    "Hidup itu seperti koding, kalau error cek lagi.",
    "Prioritas menentukan kualitas hidupmu.",
    "Jangan takut gagal, takutlah tidak mencoba.",
    "Nangis sebentar nggak apa-apa, habis itu bangkit lagi. 🌧️",
    "Gapapa pelan-pelan, yang penting nggak mundur. 🫂",
    "Hari ini berat ya? Kamu hebat sudah bertahan.",
    "Peluk jauh buat kamu yang lagi capek tapi tetap berusaha.",
    "Istirahatlah, jangan berhenti.",
    "Dunia kadang jahat, tapi kamu harus tetap baik.",
    "Tarik napas. Ini cuma satu hari yang buruk, bukan kehidupan yang buruk.",
    "Kadang 'oke' untuk tidak merasa 'oke'.",
    "Hati boleh patah, tapi mimpi jangan sampai kalah.",
    "Sendirian bukan berarti kesepian. Itu waktu untuk tumbuh.",
    "Lelah fisik bisa tidur, lelah hati butuh waktu.",
    "Gapapa kalau belum sampai, yang penting masih jalan.",
    "Menangis itu tanda kamu manusia, bukan tanda lemah.",
    "Badai pasti berlalu, pelangi menunggu.",
    "Maafkan dirimu yang kemarin, dia sudah berusaha.",
    "Jangan terlalu keras pada dirimu sendiri.",
    "Simpan sedihmu, tunjukkan senyummu.",
    "Setiap luka punya cerita, dan setiap cerita mendewasakan.",
    "Gelap malam akan berganti terang pagi.",
    "Kamu berharga, jangan biarkan siapapun meragukannya.",
    "Balas dendam terbaik adalah menjadi sukses. 😎",
    "Stop stalking, start studying. Upgrade dirimu!",
    "Dia masa lalu, kesuksesan adalah masa depan. Pilih mana?",
    "Jangan biarkan galau menghancurkan nilaimu. Rugi!",
    "Buktikan kamu bisa bahagia dan sukses tanpa dia.",
    "Jodoh pasti bertemu, tapi tugas harus selesai dulu.",
    "Fokus ke karir, cinta yang berkelas akan datang.",
    "Jangan nangisin orang yang lagi ketawa sama orang lain.",
    "Cinta boleh gagal, tapi studi harus final.",
    "Jadikan patah hati bahan bakar prestasimu.",
    "Dia nggak mikirin kamu, kenapa kamu mikirin dia?",
    "Move on itu proses, nikmati saja sambil belajar.",
    "Mantan itu alumni hati, sudah lulus jangan daftar lagi.",
    "Lebih baik capek belajar daripada capek berharap.",
    "Tunjukkan versi terbaikmu sampai dia menyesal.",
    "Cinta diri sendiri sebelum mencintai orang lain.",
    "Jangan turunkan standarmu, naikkan kualitasmu.",
    "Galau secukupnya, produktif selebihnya.",
    "Hati butuh waktu, otak butuh ilmu.",
    "Jomblo itu free trial masa depan sukses.",
    "Senyum dulu! Dunia butuh energi positifmu hari ini. ✨",
    "Hari ini indah, tugas lancar, rejeki aman. Alhamdulillah.",
    "Good mood = Good productivity. Yuk nikmati!",
    "Hidup lagi asik-asiknya. Jangan lupa bersyukur! 🥳",
    "Kamu keren banget hari ini! Pertahankan vibes-nya.",
    "Rejeki nggak akan ketuker, santai saja.",
    "Nikmati hal-hal kecil hari ini.",
    "Bahagia itu sederhana, tugas selesai contohnya.",
    "Terima kasih diriku, sudah berjuang sejauh ini.",
    "Energi positif menarik hasil positif.",
    "Hari ini adalah hadiah, makanya disebut Present.",
    "Tersenyumlah, itu ibadah termudah.",
    "Rayakan setiap kemenangan kecil.",
    "Hidup terlalu singkat untuk mengeluh.",
    "Bersyukur adalah magnet keajaiban.",
    "Semesta mendukungmu hari ini.",
    "Jadilah matahari bagi orang lain.",
    "Mood bagus, kerjaan beres, hati senang.",
    "Makan enak, tidur nyenyak, tugas kelar.",
    "Kamu adalah alasan seseorang tersenyum hari ini.",
    "Ingat, cicilan masa depan menanti. Kerja! 💸",
    "Rebahan tidak akan membuatmu kaya.",
    "Otak butuh asupan, bukan cuma harapan.",
    "Jangan jadi beban keluarga, jadilah tulang punggung.",
    "Skincare mahal, makanya harus sukses.",
    "Belajar itu capek, tapi miskin lebih capek.",
    "Gas terus, rem blong!",
    "Pura-pura sibuk sampai beneran sukses.",
    "Ingat kata tukang parkir: Mundur, mundur (kalau nyerah).",
    "Tugas ini tidak seberat rindu, kok.",
    "Dompet tebal adalah motivasi terbaik.",
    "Jangan lupa napas, jangan lupa tugas.",
    "Wifi lancar, tugas harus kelar.",
    "Tetap ilmu padi abangkuh! 🌾",
    "Menyala tugasku! 🔥",
    "Jangan kasih kendor! Dunia nggak nungguin kamu siap.",
    "Capek? Istirahat. Nyerah? Bukan opsi.",
    "Buktikan kalau omongan mereka salah besar.",
    "Mimpimu terlalu mahal untuk diraih dengan rebahan.",
    "Gaspol! Rem blong! Tabrak semua tantangan!",
    "Hari ini berjuang, besok jadi pemenang.",
    "Kalau orang lain bisa, kamu harusnya lebih bisa.",
    "Jangan jadi rata-rata, jadilah luar biasa.",
    "Waktu terus berjalan, jangan mau ketinggalan.",
    "Fokus pada tujuan, bukan pada hambatan.",
    "Keringatmu hari ini adalah senyummu di masa depan.",
    "Jadilah singa, jangan mau jadi domba.",
    "Sukses itu balas dendam yang paling elegan.",
    "Bangun tidur, kejar mimpi, ulangi.",
    "Mental baja, hati sutra, rejeki lancar.",
    "Jangan banyak alasan, banyakin pembuktian.",
    "Tugas numpuk? Selesaikan satu per satu, bukan dipikirin doang.",
    "Disiplin itu berat, tapi penyesalan jauh lebih berat.",
    "Jadilah versi dirimu yang bikin mantan nyesel.",
    "Hajar terus sampai sukses jadi kebiasaan.",
    "Ilmu adalah harta yang nggak bakal dicuri orang.",
    "Padi semakin berisi semakin merunduk. Tetap rendah hati.",
    "Proses tidak pernah mengkhianati hasil, sabar ya.",
    "Investasi terbaik adalah leher ke atas (belajar).",
    "Jangan takut salah, takutlah kalau nggak pernah nyoba.",
    "Kesuksesan adalah kumpulan kebiasaan kecil yang diulang.",
    "Hidup itu 10% kejadian, 90% respon kita.",
    "Bekerjalah dalam diam, biarkan kesuksesan yang berisik.",
    "Kualitas diri menentukan kualitas hidup.",
    "Jangan bandingkan bab 1-mu dengan bab 10 orang lain.",
    "Gagal itu bumbu kehidupan, sukses itu hidangan utamanya.",
    "Jadilah solusi, bukan polusi.",
    "Waktu adalah uang, tapi uang nggak bisa beli waktu.",
    "Sopan santun adalah mata uang yang berlaku di mana saja.",
    "Belajar bukan untuk ujian, tapi untuk kehidupan.",
    "Jangan menunggu sempurna untuk memulai.",
    "Jarak antara mimpi dan kenyataan adalah tindakan.",
    "Keberuntungan adalah pertemuan antara persiapan dan kesempatan.",
    "Hidup cuma sekali, buatlah berarti.",
    "Jadilah orang yang dirindukan, bukan yang dihindari.",
    "Nggak semua hari harus cerah, hujan pun punya peran.",
    "Gapapa nggak oke hari ini, besok kita coba lagi.",
    "Peluk diri sendiri, kamu sudah bertahan sejauh ini.",
    "Kadang menangis itu cara mata berbicara saat mulut terdiam.",
    "Istirahatlah, jiwamu juga butuh jeda.",
    "Jangan terlalu keras sama diri sendiri, kamu manusia bukan robot.",
    "Luka hari ini adalah kekuatan di masa depan.",
    "Tarik napas dalam-dalam, hembuskan bebanmu.",
    "Semua akan baik-baik saja, mungkin tidak sekarang, tapi nanti.",
    "Terima kasih sudah kuat sampai detik ini.",
    "Sendiri itu tenang, bukan berarti kesepian.",
    "Sembuhkan lukamu sebelum mencintai orang lain.",
    "Langit mendung bukan berarti akan hujan selamanya.",
    "Kadang melepaskan adalah cara terbaik untuk bertahan.",
    "Maafkan masa lalumu, dia sudah berlalu.",
    "Jangan pendam sendiri, bicaralah pada Tuhan atau sahabat.",
    "Kamu berhak bahagia, ingat itu.",
    "Gapapa jalan pelan, kura-kura pun sampai garis finish.",
    "Jatuh 7 kali, bangkit 8 kali.",
    "Hati yang hancur adalah celah bagi cahaya untuk masuk.",
    "Dia cuma satu bab dalam bukumu, bukan judul bukunya.",
    "Jangan stalking! Hatimu butuh proteksi.",
    "Mantan itu masa lalu, masa depanmu masih suci.",
    "Buang kenangannya, ambil pelajarannya.",
    "Jodoh orang lain jangan dipikirin terus.",
    "Cinta yang tepat nggak akan bikin kamu memelas.",
    "Fokus karir dulu, cinta berkelas akan mengikuti.",
    "Jangan nangisin orang yang lagi ketawa bareng orang lain.",
    "Upgrade diri biar dapet spek dewa/dewi.",
    "Logika harus jalan kalau hati mulai ugal-ugalan.",
    "Kamu terlalu berharga buat jadi opsi kedua.",
    "Putus cinta bukan akhir dunia, tapi awal kebebasan.",
    "Jomblo itu status, bahagia itu pilihan.",
    "Tuhan mematahkan hatimu untuk menyelamatkan jiwamu.",
    "Block kontaknya, buka lembaran baru.",
    "Rejeki nggak akan ketuker, apalagi jodoh.",
    "Dia rugi kehilanganmu, kamu untung kehilangan dia.",
    "Jangan turunkan standarmu karena kesepian.",
    "Cinta diri sendiri adalah cinta yang paling awet.",
    "Move on itu tanda kedewasaan.",
    "Alhamdulillah, masih bisa napas gratis hari ini.",
    "Senyummu adalah sedekah termudah.",
    "Nikmati kopi/tehmu, hidup itu indah.",
    "Hari ini penuh berkah, yuk semangat!",
    "Energi positif menarik hal-hal positif.",
    "Bahagia itu sederhana, sesederhana tugas kelar.",
    "Terima kasih Tuhan untuk hari yang cerah ini.",
    "Kamu adalah alasan seseorang tersenyum hari ini.",
    "Rejeki hari ini: Sehat, waras, dan kenyang.",
    "Jadilah matahari yang menyinari sekitarmu.",
    "Good vibes only! 🌈",
    "Rayakan kemenangan kecilmu hari ini.",
    "Hidup itu asik kalau kita pandai bersyukur.",
    "Tebarkan kebaikan, tuai kebahagiaan.",
    "Kamu istimewa, jangan lupa itu.",
    "Mood bagus = Rejeki bagus.",
    "Fokus pada hal-hal baik.",
    "Syukuri apa yang ada, semangat untuk yang belum ada.",
    "Setiap detik adalah anugerah.",
    "Hidup ini indah, jangan dibuat rumit.",
    "Kerja keraslah sampai tetanggamu kira kamu pesugihan.",
    "Dompet kosong adalah motivasi terkuat.",
    "Jangan lupa napas, nanti mati.",
    "Rebahan sebentar, sukses kemudian (tapi boong).",
    "Hidup seperti Larry 🦞",
    "Mending turu daripada mumet.",
    "Tugas ini disponsori oleh air mata dan kopi instan.",
    "Ingat, cicilan nggak bisa dibayar pakai 'Terima Kasih'.",
    "Mau kaya tapi males? Mimpi!",
    "Kalau capek, coba lihat saldo ATM.",
    "Jodoh nggak ke mana, saingannya yang di mana-mana.",
    "Tetap ilmu padi: Semakin berisi, semakin merunduk (kalau ngantuk).",
    "Jangan jadi beban keluarga, minimal cuci piring sendiri.",
    "Skincare mahal woy, semangat kerjanya!",
    "Belajar itu berat, tapi lebih berat ngangkat beban hidup.",
    "Diam itu emas, tapi sukses itu berlian. Gas!",
    "Jangan mau kalah sama ayam, dia bangun pagi terus.",
    "Mimpimu nggak butuh penonton, butuhnya pemain.",
    "Kalau capek lari, jalan. Kalau capek jalan, merangkak. Jangan berhenti.",
    "Hasil tidak pernah berkhianat pada yang berkeringat.",
    "Jadilah bukti berjalan bahwa usaha itu nyata.",
    "Dunia ini keras, makanya kamu harus lebih keras.",
    "Tunda kesenanganmu sekarang, nikmati kemewahan nanti.",
    "Fokus! Notifikasi HP nggak bikin kamu kaya.",
    "Jadilah pemenang di ceritamu sendiri.",
    "Kerja keras sampai idola kamu jadi saingan kamu.",
    "Jangan kasih ruang buat rasa malas.",
    "Setiap detik yang kamu buang adalah keuntungan buat sainganmu.",
    "Bantai tugasnya sekarang, rebahan dengan tenang nanti.",
    "Mental juara itu dibentuk, bukan dilahirkan.",
    "Jangan cuma jadi penikmat, jadilah pencipta.",
    "Kalau jalannya mudah, mungkin kamu salah jalan.",
    "Kesuksesan ada di seberang tembok rasa takut.",
    "Berani bermimpi, berani eksekusi.",
    "Tugas numpuk? Itu tanda kamu sedang naik level.",
    "Pohon yang tinggi anginnya pasti kencang. Sabar.",
    "Bukan seberapa cepat, tapi seberapa konsisten.",
    "Ilmu padi: Semakin berisi, semakin rendah hati.",
    "Jangan menilai buku dari sampulnya, bacalah isinya.",
    "Sabar itu ilmu tingkat tinggi, belajarnya setiap hari.",
    "Kejujuran adalah mata uang yang berlaku di mana saja.",
    "Hidup itu seni menggambar tanpa penghapus.",
    "Jangan menjelaskan dirimu pada orang yang tidak mau mengerti.",
    "Diam adalah jawaban terbaik untuk orang bodoh.",
    "Waktu akan menjawab apa yang tidak bisa dijawab logika.",
    "Lidahmu jangan kamu biarkan menyebut kekurangan orang lain.",
    "Kebaikan yang kamu tanam akan kamu tuai suatu hari nanti.",
    "Belajar mengalah sampai tak seorang pun bisa mengalahkanmu.",
    "Harta yang paling berharga adalah ketenangan hati.",
    "Jadilah seperti air, lembut tapi bisa memecah batu.",
    "Orang kuat bukan yang bisa membanting lawan, tapi yang bisa menahan amarah.",
    "Balaslah keburukan dengan kebaikan, itu kelas.",
    "Pendidikan bukan persiapan hidup, pendidikan adalah hidup itu sendiri.",
    "Jangan takut berjalan lambat, takutlah jika hanya berdiri diam.",
    "Pengalaman adalah guru yang paling sadis, ujian dulu baru pelajaran.",
    "Hujan di luar reda, hujan di mata kapan?",
    "Gapapa, hari ini kamu bertahan saja itu sudah prestasi.",
    "Kadang rumah bukan tempat pulang yang paling nyaman.",
    "Tarik selimut, lupakan dunia sejenak. Kamu butuh jeda.",
    "Terlalu banyak memikirkan perasaan orang lain sampai lupa diri sendiri.",
    "Lukanya nggak berdarah, tapi sakitnya sampai ke tulang.",
    "Menangislah, air mata itu doa saat mulut tak sanggup bicara.",
    "Sedang berada di fase 'yasudahlah' untuk segalanya.",
    "Ternyata pura-pura bahagia itu melelahkan ya.",
    "Malam adalah teman bagi mereka yang memendam rasa.",
    "Semoga hatimu segera membaik dari hal yang tak kau ceritakan.",
    "Kadang sepi itu menenangkan, tapi seringkali mencekam.",
    "Aku memaafkanmu, tapi aku tidak melupakan rasanya.",
    "Berlari dari kenyataan hanya akan membuatmu lelah di tempat.",
    "Langit tak selamanya abu-abu, sabar ya.",
    "Tidur adalah pelarian terbaik dari isi kepala yang berisik.",
    "Gapapa kalau nggak dapet validasi orang lain.",
    "Kamu berhak bilang 'nggak' kalau memang nggak sanggup.",
    "Lelah itu manusiawi, istirahatlah.",
    "Besok pagi, matahari akan terbit lagi. Kamu juga harus bangkit.",
    "Cie yang masih stalking padahal udah diblokir.",
    "Kenangan itu kayak hantu, muncul pas lagi sendirian.",
    "Dia udah bahagia sama yang lain, kamu kapan?",
    "Move on itu bukan melupakan, tapi mengikhlaskan.",
    "Jangan cari dia di masa depan, dia tertinggal di masa lalu.",
    "Rindu yang tak tersampaikan akan jadi penyakit.",
    "Cinta boleh, bodoh jangan. Logika dipakai woy!",
    "Dia cuma singgah, bukan sungguh.",
    "Berhenti nunggu chat dari orang yang prioritasin orang lain.",
    "Mantan itu kayak sampah, jangan dipungut lagi.",
    "Lebih baik sendiri daripada berdua tapi kesepian.",
    "Tuhan memisahkan karena dia bukan yang terbaik buatmu.",
    "Fokus skripsi/kerjaan, jodoh di tangan Tuhan (dan usaha).",
    "Jangan jadi badut di kisah cinta orang lain.",
    "Cintailah orang yang mencintaimu, bukan yang menyakitimu.",
    "Hati-hati, rindu bisa bikin kamu chat duluan. Tahan!",
    "Dia happy story, kamu sad story. Nggak level.",
    "Upgrade diri biar dapet yang premium.",
    "Putus cinta satu, tumbuh seribu (masalah lain). Canda.",
    "Jomblo itu bukan nasib, itu prinsip (padahal nggak laku).",
    "Wih, hari ini cakep banget! Semangat!",
    "Alhamdulillah, rejeki anak sholeh/sholehah.",
    "Senyum itu gratis, tapi efeknya mahal.",
    "Hari ini makan enak yuk, self-reward!",
    "Kamu adalah alasan seseorang bersyukur hari ini.",
    "Energi positifmu nular banget, pertahankan!",
    "Bahagia itu diciptakan, bukan dicari.",
    "Tugas kelar, hati mekar. Asik!",
    "Nikmati prosesnya, syukuri hasilnya.",
    "Dunia butuh senyum manismu.",
    "Rejeki hari ini: Internet lancar dan kopi enak.",
    "Jadilah pelangi di awan mendung orang lain.",
    "Hidup itu indah kalau kita nggak kebanyakan mikir.",
    "Semesta lagi berpihak padamu hari ini.",
    "Jangan lupa bahagia, itu kewajiban.",
    "Mood booster terbaik adalah saldo bertambah.",
    "Bersyukur bikin hidup terasa cukup.",
    "Ayo tertawa, biar awet muda.",
    "Kamu unik, kamu spesial, kamu berharga.",
    "Makan kenyang, hati senang, pikiran tenang.",
    "Kerja, kerja, kerja! Tipes.",
    "Duit nggak dibawa mati, tapi kalau nggak ada duit rasanya mau mati.",
    "Motivasi hari ini: Cicilan Paylater.",
    "Mending rakit PC daripada rakit rumah tangga.",
    "Hidup itu seperti roda, kadang di atas, kadang diinjek.",
    "Jangan lupa napas, oksigen masih gratis.",
    "Dompet menipis, harapan menipis, tapi perut tetep eksis.",
    "Kalau ada yang nyari, bilang aku lagi nyari duit.",
    "Rebahan adalah passion, sukses adalah obsession.",
    "Info loker: Jaga lilin, gaji UMR.",
    "Belajar itu perlu, tapi tidur itu candu.",
    "Manusia boleh berencana, saldo yang menentukan.",
    "Tetaplah hidup walau tidak berguna (eh berguna kok!).",
    "Kata dokter kurangin manis, makanya aku jangan ngaca terus.",
    "Otak: Belajar! Hati: Main HP! Mata: Tidur!",
    "Pura-pura kaya itu butuh modal gede.",
    "Masa depan cerah, secerah jidat saya.",
    "Capek kerja? Coba jadi rafathar.",
    "Hidup dibawa santai aja, kalau dibawa lari capek.",
    "Semangat! Ingat kuota internet makin mahal.",
    "Ingat, check-out keranjang oren butuh dana, bukan cuma doa.",
    "Mau healing tapi dompet kering? Kerja dulu bestie.",
    "Jadilah kaya biar kalau sedih bisa nangis di Paris, bukan di pojokan kamar.",
    "Motivasi terbesar: Biar nggak dipandang sebelah mata sama tetangga.",
    "Rebahan itu enak, tapi punya duit sendiri itu lebih enak.",
    "Jangan nunggu mood, mood nggak bakal bayarin tagihanmu.",
    "Mimpi setinggi langit, tapi kalau males ya tetep napak tanah.",
    "Kerja keraslah sampai harga barang nggak jadi masalah.",
    "Kalau kamu berhenti sekarang, sainganmu bakal tepuk tangan.",
    "Ingat wajah orang tuamu, mereka layak dapat menantu sukses (eh, anak sukses).",
    "Duit bukan segalanya, tapi segalanya butuh duit. Fakta.",
    "Jangan jadi beban negara, minimal jangan jadi beban orang tua.",
    "Gaya elit, ekonomi sulit? Jangan sampai kejadian.",
    "Sukses itu wajib, biar kalau reuni nggak minder.",
    "Ayo bangun! Rejeki dipatok ayam kalau kesiangan (klise tapi bener).",
    "Tabungan masa depan nggak akan keisi sendiri.",
    "Mau traktir ortu makan enak kan? Yuk semangat!",
    "Fokus! Biar nanti bisa beli rumah cash, aamiin.",
    "Jangan sampai gaya hidupmu lebih tinggi dari kemampuanmu.",
    "Kesuksesanmu adalah tamparan terbaik buat yang pernah ngeremehin.",
    "Gapapa istirahat, baterai HP aja perlu dicas, apalagi kamu.",
    "Tarik napas... Masalah hari ini cukup untuk hari ini.",
    "Jangan lupa makan, lambungmu nggak sekuat mentalmu.",
    "Kamu udah keren banget lho bisa bertahan sampai hari ini.",
    "Dunia nggak akan runtuh cuma karena kamu salah dikit.",
    "Tidur yang cukup, mata pandamu butuh pertolongan.",
    "Minum air putih, biar ginjal aman, pikiran tenang.",
    "Nggak usah dengerin orang lain, mereka nggak bayarin hidupmu.",
    "Pelan-pelan asal kelakon. Nggak usah lari kalau kaki sakit.",
    "Sayangi dirimu sendiri sebelum berharap disayang orang lain.",
    "Kadang 'bodo amat' itu perlu demi kewarasan mental.",
    "Kamu cukup. Kamu berharga. Kamu bisa.",
    "Jangan overthinking, yang kamu takutin belum tentu kejadian.",
    "Hujan pasti reda, capek pasti ada obatnya.",
    "Kalau hari ini gagal, besok masih ada matahari terbit.",
    "Fisik boleh lelah, tapi harapan jangan sampai punah.",
    "Rayakan dirimu sekecil apapun progresnya.",
    "Jaga kesehatan, sakit itu mahal jendral!",
    "Luangkan waktu buat hobi, biar nggak stres melulu.",
    "Kamu berhak bilang 'tidak' kalau memang nggak mau.",
    "Dia udah update story sama yang lain, kamu masih pantengin profilnya?",
    "Jatuh cinta boleh, bodoh jangan. Pakai logikanya.",
    "Mending sibuk ngejar karir daripada ngejar orang yang nggak mau dikejar.",
    "Stop jadi badut buat orang yang cuma anggep kamu penonton.",
    "Kalau dia jodohmu, dia nggak akan bikin kamu ngemis perhatian.",
    "Prioritaskan yang memprioritaskanmu. Titik.",
    "Hapus chat-nya, arsip kenangannya, fokus ke depan.",
    "Kamu terlalu 'mahal' buat orang yang sukanya diskonan.",
    "Jomblo berkualitas lebih baik daripada pacaran makan hati.",
    "Cinta itu bonus, sukses itu harus.",
    "Jangan biarkan satu orang merusak masa depanmu.",
    "Mantan itu spion, sesekali dilirik boleh, tapi jangan dipelototin terus (nabrak!).",
    "Kebahagiaanmu bukan tanggung jawab pacar, tapi tanggung jawabmu.",
    "Semesta memisahkan karena kamu layak dapat yang lebih baik.",
    "Udah, nggak usah kode-kodean di story. Dia nggak peka.",
    "Investasi ke diri sendiri nggak akan pernah rugi, beda sama investasi ke doi.",
    "Fokus upgrade diri, nanti yang berkualitas bakal antri.",
    "Jangan buang air matamu buat orang yang nggak tau nilaimu.",
    "Sendiri itu bebas, bisa ngapain aja tanpa laporan.",
    "Hati-hati, kesepian sering bikin salah pilih orang.",
    "Hidup itu berat, yang ringan itu dosa.",
    "Kalau ada masalah, selesaikan. Kalau nggak bisa, tinggalkan tidur.",
    "Manusia merencanakan, saldo ATM yang menentukan.",
    "Kerja lah, emang mau nunggu warisan? Kalau ada sih enak.",
    "Jangan lupa senyum hari ini, biar yang iri makin panas.",
    "Tetaplah hidup walau beban hidup seberat gajah duduk.",
    "Motivasiku hari ini: Takut dimarahin emak.",
    "Mending ketinggalan mantan daripada ketinggalan diskon.",
    "Definisi dewasa: Banyak cicilan tapi tetap ketawa.",
    "Otak: 'Ayo produktif!', Badan: 'Kasur posesif banget nih'.",
    "Belajar itu emang bikin pusing, tapi kalau nggak belajar bikin pusing orang tua.",
    "Cita-cita jadi miliarder, hobi check-out barang nggak penting.",
    "Semangat! Ingat kuota internet nggak gratis.",
    "Kalau capek, inget ada orang yang nunggu kamu gagal. Jangan kasih kepuasan!",
    "Dompet makin tipis, harapan makin kritis, ayo optimis!",
    "Jangan kebanyakan mimpi, nanti tidurnya kebablasan.",
    "Hidup emang banyak cobaan, kalau banyak cucian itu laundry.",
    "Tetap santuy walau deadline menghantui.",
    "Uang nggak dibawa mati, tapi kalau nggak punya uang rasanya mau mati.",
    "Sabar itu ada batasnya, kalau nggak ada batasnya itu laut.",
    "Mimpi doang, gerak kagak. Situ patung pancoran?",
    "Scroll TikTok 3 jam kuat, belajar 30 menit langsung bengek.",
    "Sainganmu lagi upgrade skill, kamu masih sibuk upgrade skin game.",
    "Jangan ngeluh capek kalau dari pagi cuma pindah posisi tidur.",
    "Mau sukses jalur instan? Mi instan aja perlu direbus dulu, Bestie.",
    "Kurangi gaya, banyakin karya. Dompetmu menangis tuh.",
    "Stop halu! Pangeran berkuda putih nggak bakal jemput orang yang belum mandi.",
    "Motivasi terbesar: Sadar diri bukan anak Sultan, jadi harus kerja keras.",
    "Rebahan tidak akan mengubah nasib, cuma mengubah bentuk badan.",
    "Jangan nunggu mood bagus, emangnya mood bisa bayar tagihan?",
    "Mental yupi (lembek) jangan harap dapet gaji besi.",
    "Kalau malas, jangan punya mimpi tinggi-tinggi. Nanti jatuh, sakit.",
    "Hidup itu keras, yang lunak cuma pipi kamu.",
    "Udah gede, masa masih jadi beban keluarga? Minimal cuci piring lah.",
    "Dunia nggak butuh alasanmu, dunia butuh hasil kerjamu.",
    "Gaya elit, ekonomi sulit. Tobat yuk bisa yuk.",
    "Jangan kebanyakan drama, hidupmu bukan sinetron indosiar.",
    "Fokus woy! Mantan udah mau nikah, kamu masih gini-gini aja?",
    "Sukses itu aksi, bukan cuma update status 'Bismillah' doang.",
    "Ingat, kuota internet nggak dibayar pakai daun.",
    "Deadline lebih seram daripada hantu, kerjain sekarang!",
    "Revisi adalah jalan ninjaku menuju kesuksesan (dan kebotakan).",
    "Skripsi/Tugas itu dikerjain, bukan diratapi tiap malam.",
    "Dosen/Bos nggak butuh 'maaf', butuhnya file dikirim.",
    "SKS: Sistem Kebut Semalam (Jangan ditiru, tapi seru sih).",
    "Otak: 'Ayo produktif!', Mata: '5 menit lagi ya tidurnya'.",
    "Wisuda/Gajian masih lama, tapi semangat harus ada sekarang.",
    "Nilai jelek bisa diperbaiki, tapi waktu yang hilang nggak bisa diganti.",
    "Jangan jadi mahasiswa kupu-kupu (kuliah pulang), jadilah kura-kura (kuliah rapat).",
    "Laptop udah nyala, tapi yang dibuka malah Youtube. Hayo ngaku!",
    "Ingat wajah orang tua pas bayar UKT/SPP. Masih tega malas?",
    "Kerja cerdas, bukan cuma kerja keras (biar nggak tipes).",
    "Presentasi besok? Tenang, panik aja dulu.",
    "Tugas numpuk itu seni, seni menahan emosi.",
    "Kalau error, jangan banting laptop. Cicilannya belum lunas.",
    "Dewasa itu jebakan batman, isinya tagihan semua.",
    "Punggung encok adalah lambang kedewasaan sejati.",
    "Ingin kembali ke masa TK, beban terberat cuma PR mewarnai.",
    "Tidur adalah cuti singkat dari kejamnya dunia.",
    "Gaji cuma numpang lewat kayak iklan Youtube.",
    "Capek? Sama. Tapi kalau berhenti, siapa yang kasih makan kucing?",
    "Hidup lagi capek-capeknya, eh sampo habis, sabun habis.",
    "Definisi kaya: Check-out belanjaan tanpa mikir tanggal tua.",
    "Kadang pengen jadi batu aja, diam dan nggak punya cicilan.",
    "Manusia merencanakan, saldo ATM yang menentukan.",
    "Healing terbaik adalah transferan masuk.",
    "Pulang kerja pengennya disambut uang kaget, bukan cucian piring.",
    "Dewasa itu harus pinter akting: Pura-pura kuat, pura-pura punya duit.",
    "Liburan itu mitos, lembur itu fakta.",
    "Tetaplah bernapas walau rasanya sesak napas lihat pengeluaran.",
    "Hidup itu kayak angkot, ngetem mulu kapan jalannya?",
    "Jadilah seperti martabak: Spesial dan manis (tapi jangan dikacangin).",
    "Kalau ada yang nyariin, bilang aku lagi nyari wangsit.",
    "Tetap santuy walau dunia sedang tidak yoi.",
    "Motivasi hari ini: Pengen beli Seblak prasmanan bebas ambil.",
    "Jangan lupa napas, oksigen masih gratis (belum dipajakin).",
    "Mending turu (tidur) daripada tahu kenyataan.",
    "Dompet makin tipis, perut makin eksis. Hukum alam.",
    "Kalau jodoh nggak ke mana, tapi saingannya yang di mana-mana.",
    "Hidup berjalan seperti roda, kadang di atas, kadang bannya bocor.",
    "Kata dokter kurangin manis, makanya aku jarang ngaca.",
    "Masa depan cerah, secerah jidat saya kena lampu.",
    "Tetap ilmu padi: Semakin berisi, semakin merunduk (karena ngantuk).",
    "Jomblo itu prinsip. Prinsip belum laku.",
    "Semangat! Ingat, kamu belum punya pulau pribadi.",
    "Jangan bandingkan 'Behind The Scene' hidupmu dengan 'Highlight' orang lain.",
    "Rumput tetangga lebih hijau karena dia pakai filter Instagram.",
    "Scroll TikTok boleh, tapi ingat jam dinding terus berputar.",
    "Dia sukses di umur 20? Keren. Kamu sukses di umur 30? Juga keren. Tiap orang punya zonanya.",
    "Berhenti stalking kehidupan orang yang nggak peduli sama kamu.",
    "HP canggih, kuota banyak, masa dompet kosong? Gunakan buat cuan!",
    "Likes di sosmed nggak bisa ditukar beras, fokus di dunia nyata.",
    "Jangan jadi penonton kesuksesan orang lain, mulailah syuting filmmu sendiri.",
    "Dunia maya itu panggung sandiwara, dunia nyata tempat kita bekerja.",
    "Matikan HP, nyalakan mimpi. Kerjakan tugasmu.",
    "FOMO (Fear Of Missing Out) itu penyakit dompet dan mental.",
    "Postingan bahagia belum tentu aslinya bahagia. Jangan iri.",
    "Jadilah influencer buat diri sendiri dulu sebelum influence orang lain.",
    "Notifikasi terbaik adalah notifikasi transferan masuk.",
    "Filter wajah boleh, tapi hati jangan diedit-edit.",
    "Rebahan itu enak, tapi punya uang sendiri itu candu.",
    "Kasur emang posesif, tapi masa depanmu lebih agresif menuntut.",
    "Mau sukses jalur langit? Doa kenceng, usaha juga harus kenceng bestie.",
    "Cita-cita jadi CEO, hobi menunda pekerjaan. Lawak lu.",
    "Jangan sampai tuamu nanti cuma cerita 'Dulu aku sebenarnya bisa, tapi males'.",
    "Bangun! Rejeki nggak bakal ngetuk pintu kamar kalau kamu kunci dari dalam.",
    "Kalau malas, ingatlah harga tiket konser idola makin mahal.",
    "Sukses butuh konsistensi, bukan cuma motivasi pas lagi mood.",
    "Mending capek kerja sekarang daripada capek nyari lowongan nanti.",
    "Bergeraklah walau cuma satu inci, daripada diam jadi patung.",
    "Setan aja rajin ngegoda, masa manusia malas berusaha?",
    "Otak encer kalau nggak dipakai bakal beku juga.",
    "Tugas ini kecil, kemalasanmu yang membuatnya terlihat raksasa.",
    "Ayo produktif! Biar bisa pamer pencapaian, bukan pamer keluhan.",
    "Jatah gagalmu harus dihabiskan selagi muda, biar tua tinggal panen.",
    "Hidup itu murah, gengsi yang bikin mahal.",
    "Dewasa itu ketika kamu lebih milih tidur daripada nongkrong nggak jelas.",
    "Jangan menua tanpa arti, menualah dengan karya.",
    "Teman banyak itu asik, tapi teman yang ada pas susah itu langka.",
    "Lingkunganmu mempengaruhi masa depanmu. Pilih circle yang sehat.",
    "Uang bukan segalanya, tapi segalanya jadi ribet tanpa uang.",
    "Investasi leher ke atas (ilmu) return-nya seumur hidup.",
    "Jangan kerja keras cari muka, kerja keraslah cari nafkah.",
    "Sopan santun adalah kecantikan yang tidak akan tua.",
    "Janji manis orang lain seringkali mengandung diabetes (penyakit hati).",
    "Berhentilah menyalahkan keadaan, mulailah ciptakan peluang.",
    "Kadang kita harus tega sama diri sendiri biar bisa maju.",
    "Waktu adalah hakim yang paling adil.",
    "Jangan takut beda, takutlah kalau sama terus kayak orang lain.",
    "Keputusanmu hari ini menentukan siapa kamu 5 tahun lagi.",
    "Hidup lagi capek-capeknya, eh ada yang ngajak MLM.",
    "Motivasi hari ini: Ingin beli rumah biar nggak diusir mertua (canda).",
    "Manusia boleh berencana, tapi saldo ATM kadang bercanda.",
    "Sabar itu ada batasnya, kalau nggak ada batasnya itu jalan tol.",
    "Ingin hati memeluk gunung, apa daya tangan masih megang HP.",
    "Mending turu, timbang mumet mikirin negara.",
    "Diet mulai besok (wacana abadi).",
    "Kalau ada yang ngomongin di belakang, kentutin aja.",
    "Dompetku seperti bawang, dibuka bikin nangis.",
    "Kerja bagai kuda, digaji kayak kura-kura. Semangat!",
    "Jangan lupa napas, oksigen masih gratis belum dipajakin.",
    "Tetaplah hidup walau cuma jadi beban (eh jangan dong).",
    "Cermin ajaib, katakan siapa yang paling rajin? (Bukan aku).",
    "Jodoh emang di tangan Tuhan, tapi kalau nggak diambil ya di tangan orang.",
    "Pura-pura bahagia itu butuh tenaga, mending makan.",
    "Rencana liburan mulu, realisasi nol. Situ travel agent?",
    "Wacana adalah doa yang tertunda karena kemalasan.",
    "Jangan kebanyakan 'nanti dulu', nanti taunya udah tua.",
    "Sukses itu butuh aksi, bukan cuma update story 'Bismillah'.",
    "Mimpi boleh setinggi langit, tapi kalau kaki nggak gerak, ya tetep di bumi.",
    "Kurangi rapat (rapatkan barisan rebahan), perbanyak eksekusi.",
    "Ide 1 Miliar, Eksekusi 1 Rupiah. Rugi dong!",
    "Janji pada diri sendiri aja diingkari, apalagi janji ke orang lain.",
    "Diet mulai besok, belajar mulai lusa, suksesnya di akhirat?",
    "Jangan bangga jadi 'Idea Man' kalau nggak pernah jadi 'Action Man'.",
    "Tugas nggak akan selesai dengan dipandangi.",
    "Mending gagal pas nyoba, daripada nyesel nggak pernah nyoba.",
    "Stop bilang 'aku nggak bisa' sebelum nyoba minimal 5 kali.",
    "Rumus sukses: Mulai aja dulu, sempurnakan sambil jalan.",
    "Motivasi tanpa aksi itu cuma halusinasi.",
    "Teman itu ada masa kadaluarsanya, nggak usah kaget kalau ada yang pergi.",
    "Hati-hati curhat, screenshoot jahat berkeliaran.",
    "Circle kecil nggak masalah, yang penting isinya daging semua (berkualitas).",
    "Jangan jadi 'People Pleaser', kamu bukan badut ulang tahun.",
    "Teman yang baik itu yang ngajak sukses, bukan cuma ngajak nongkrong.",
    "Kalau dia cuma dateng pas butuh, kasih aja peta ke dinas sosial.",
    "Berhenti menyeberangi lautan buat orang yang nggak mau melompati genangan buat kamu.",
    "Dewasa itu sadar kalau nggak semua orang harus suka sama kita.",
    "Mending dimusuhi karena jujur, daripada disukai karena munafik.",
    "Jaga rahasiamu, bahkan bayanganmu meninggalkanmu saat gelap.",
    "Lingkungan toksik lebih bahaya dari limbah nuklir. Menjauhlah.",
    "Jangan takut kehilangan teman, takutlah kehilangan jati diri.",
    "Sahabat sejati itu langka, kalau nemu dijaga, jangan dipinjemin duit melulu.",
    "Filter temanmu seperti kamu filter foto Instagram.",
    "Sendiri lebih baik daripada dikelilingi orang yang bikin mental down.",
    "Bilang 'Nggak' itu hak asasi, jangan merasa bersalah.",
    "Kesehatan mentalmu lebih penting dari deadline (tapi deadline tetep dikerjain ya).",
    "Validasi terbaik datang dari cermin, bukan dari likes.",
    "Jangan bakar dirimu cuma buat ngangetin orang lain.",
    "Marah boleh, dendam jangan. Nanti keriput.",
    "Overthinking cuma bikin masalah yang sebenernya nggak ada.",
    "Maafkan diri sendiri karena pernah membiarkan orang lain menyakitimu.",
    "Istirahatlah sebelum tubuhmu memaksamu istirahat (sakit).",
    "Bahagia itu tanggung jawab masing-masing, jangan nitip ke orang lain.",
    "Hidup nggak harus selalu estetik, yang penting asik.",
    "Kadang obat terbaik adalah tidur 8 jam tanpa alarm.",
    "Jangan biarkan komentar 5 detik merusak mood 24 jam-mu.",
    "Kamu berhak menjauh dari apa pun yang bikin ribet.",
    "Damai itu mahal, jangan ditukar sama drama murah.",
    "Fokus pada apa yang bisa kamu kendalikan (pikiranmu), bukan cuaca atau omongan tetangga.",
    "Cinta itu buta, tapi tagihan listrik tetep harus dibaca.",
    "Jangan cari yang sempurna, cari yang mau berjuang bareng (dan punya visi).",
    "Kalau dia serius, dia bakal cari jalan. Kalau main-main, dia cari alasan.",
    "Trauma masa lalu bukan alasan buat nyakitin orang baru.",
    "Pasangan itu partner, bukan ATM berjalan atau pembantu.",
    "Komunikasi adalah kunci, kode-kodean itu buat pramuka.",
    "Cinta tak harus memiliki, tapi harus menghidupi (minimal jajan bakso).",
    "Setia itu mahal, makanya nggak bisa dilakukan orang murahan.",
    "Jangan nikah karena kesepian, nikahlah karena kesiapan.",
    "Jomblo fisabilillah, menanti jodoh yang lillah.",
    "Hati-hati, kenyamanan sesaat bisa jadi jebakan seumur hidup.",
    "Cinta produk dalam negeri, cintai dirimu sendiri.",
    "Mending jomblo berkelas daripada pacaran berkualitas rendah.",
    "Jodoh itu cerminan diri. Mau dapet yang baik? Jadilah baik dulu.",
    "Move on jalur prestasi, biar mantan nyesel sampai ke ulu hati.",
    "Sayur apa yang jago nyanyi? Kolplay.",
    "Orang sibuk belum tentu kaya, bisa jadi sibuk nyari pinjeman.",
    "Motivasi hari ini: Ingin kaya biar bisa beli omongan tetangga.",
    "Kenapa zombie kalau nyerang bareng-bareng? Karena kalau sendiri namanya zomblo.",
    "Dompetku sama bawang merah sama aja, bikin nangis.",
    "Tadi mau nabung, eh ada bakso lewat. Ya udah, nabung lemak dulu.",
    "Hidup itu seperti angry birds, kalau gagal ada aja babi yang ketawa.",
    "Jangan lupa sarapan, karena sarapan lebih enak dari harapan.",
    "Cita-cita kurus, hobi ngemil. Lawak.",
    "Kalau ada masalah, senyumin aja. Biar masalahnya bingung.",
    "Uang tidak bisa membeli kebahagiaan, tapi bisa beli nasi padang (sama aja).",
    "Mending telat nikah daripada telat angkat jemuran (kehujanan).",
    "Kerja keraslah sampai kamu nggak perlu liat harga pas beli kerupuk.",
    "Hidup itu pilihan. Mau mandi sekarang atau nanti sore?",
    "Semangat! Cicilan panci belum lunas."
];